version: '3.7'
services:
  mongo:
    container_name: db-customers
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./mongo/configs:/etc/configs
    env_file:
      - .env
  api:
    container_name: api-customers
    build:
      context: ../
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
networks:
  default:
    external:
      name: opentrace
